INFO	2020-12-08 21:33:08,555	[remote_connection.py:117]	Could not connect to port 4723 on host localhost
INFO	2020-12-08 21:33:08,555	[remote_connection.py:136]	Could not get IP address for host: localhost
WARNING	2020-12-08 21:33:12,622	[connectionpool.py:752]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024E6338F088>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2020-12-08 21:33:16,663	[connectionpool.py:752]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024E6338FA48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2020-12-08 21:33:20,705	[connectionpool.py:752]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024E633992C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
INFO	2020-12-08 21:33:35,643	[remote_connection.py:117]	Could not connect to port 4723 on host localhost
INFO	2020-12-08 21:33:35,643	[remote_connection.py:136]	Could not get IP address for host: localhost
WARNING	2020-12-08 21:33:39,704	[connectionpool.py:752]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F631AD048>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2020-12-08 21:33:43,779	[connectionpool.py:752]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F631AD9C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2020-12-08 21:33:47,842	[connectionpool.py:752]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F631B5248>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
INFO	2020-12-08 21:36:27,259	[remote_connection.py:117]	Could not connect to port 4723 on host localhost
INFO	2020-12-08 21:36:27,259	[remote_connection.py:136]	Could not get IP address for host: localhost
WARNING	2020-12-08 21:36:31,321	[connectionpool.py:752]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AC51B0D2C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2020-12-08 21:36:35,362	[connectionpool.py:752]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AC51B0DC08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2020-12-08 21:36:39,413	[connectionpool.py:752]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AC51B18488>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
INFO	2020-12-08 21:37:23,006	[remote_connection.py:117]	Could not connect to port 4723 on host 127.0.0.1
INFO	2020-12-08 21:37:23,006	[remote_connection.py:136]	Could not get IP address for host: 127.0.0.1
WARNING	2020-12-08 21:37:25,029	[connectionpool.py:752]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029C424CF288>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2020-12-08 21:37:27,052	[connectionpool.py:752]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029C424CFC08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2020-12-08 21:37:29,071	[connectionpool.py:752]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000029C424E8488>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
INFO	2020-12-08 21:39:41,438	[remote_connection.py:117]	Could not connect to port 4723 on host 127.0.0.1
INFO	2020-12-08 21:39:41,438	[remote_connection.py:136]	Could not get IP address for host: 127.0.0.1
WARNING	2020-12-08 21:39:43,462	[connectionpool.py:752]	Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A730253EC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2020-12-08 21:39:45,482	[connectionpool.py:752]	Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A73026E5C8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
WARNING	2020-12-08 21:39:47,514	[connectionpool.py:752]	Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002A73026EE08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /wd/hub/session
INFO	2020-12-08 21:45:40,120	[webpage.py:83]	点击元素：('xpath', "//*[@content-desc='Me']")
INFO	2020-12-08 21:45:40,883	[webpage.py:83]	点击元素：('id', 'com.zhiyun.cama:id/tv_login')
INFO	2020-12-08 21:45:42,523	[webpage.py:77]	输入文本：16714056631
INFO	2020-12-08 21:45:44,156	[webpage.py:77]	输入文本：00000000
INFO	2020-12-08 21:45:45,304	[webpage.py:83]	点击元素：('id', 'com.zhiyun.cama:id/tv_commit')
